# This build is used for public PR and CI builds.

trigger:
    batch: true
    branches:
        include:
            - v3.x

pr:
    branches:
        include:
            - v3.x

schedules:
    - cron: '30 10 * * *'
      displayName: Nightly at 3:30 AM PT
      always: true
      branches:
          include:
              - v3.x

resources:
    repositories:
        - repository: 1es
          type: git
          name: 1ESPipelineTemplates/1ESPipelineTemplates
          ref: refs/tags/release

extends:
    template: v1/1ES.Unofficial.PipelineTemplate.yml@1es
    parameters:
        pool:
            name: 1es-pool-azfunc-public
            image: 1es-windows-2022
            os: windows

        stages:
            - stage: WindowsUnitTests
              dependsOn: []
              jobs:
                  - template: /azure-pipelines/templates/test.yml@self

            - stage: LinuxUnitTests
              dependsOn: []
              jobs:
                  - template: /azure-pipelines/templates/test.yml@self
              pool:
                  name: 1es-pool-azfunc-public
                  image: 1es-ubuntu-22.04
                  os: linux

            - stage: Build
              dependsOn: []
              jobs:
                  - template: /azure-pipelines/templates/build.yml@self
                    parameters:
                        IsPrerelease: true
