parameters:
- name: NpmPublishTag
  displayName: 'Tag'
  type: string
  default: 'preview'
- name: NpmPublishDryRun
  displayName: 'Dry Run'
  type: boolean
  default: true

trigger: none
pr: none

resources:
  pipelines:
  - pipeline: nodeLibraryCI
    project: 'Azure Functions'
    source: azure-functions-nodejs-library.build
    branch: v4.x

jobs:
- job: Release
  pool:
    name: '1ES-Hosted-AzFunc'
    demands:
    - ImageOverride -equals MMSUbuntu20.04TLS
  steps:
  - download: nodeLibraryCI
  - task: NodeTool@0
    displayName: 'Install Node.js'
    inputs:
      versionSpec: 18.x
  - script: npm ci
    displayName: 'npm ci'
  - script: 'npm run validateRelease -- --publishTag ${{ parameters.NpmPublishTag }} --dropPath "$(Pipeline.Workspace)/nodeLibraryCI/drop"'
    displayName: 'validate release'
  - script: mv *.tgz package.tgz
    displayName: 'Rename tgz file' # because the publish command below requires an exact path
    workingDirectory: '$(Pipeline.Workspace)/nodeLibraryCI/drop'
  - task: Npm@1
    displayName: 'npm publish'
    inputs:
      command: custom
      workingDir: '$(Pipeline.Workspace)/nodeLibraryCI/drop'
      verbose: true
      customCommand: 'publish package.tgz --tag ${{ parameters.NpmPublishTag }} --dry-run ${{ lower(parameters.NpmPublishDryRun) }}'
      customEndpoint: 'Functions Node.js Library Publish'