parameters:
    - name: NpmPublishTag
      displayName: 'Tag'
      type: string
      default: 'latest'
    - name: NpmPublishDryRun
      displayName: 'Dry Run'
      type: boolean
      default: true

trigger: none
pr: none

resources:
    repositories:
        - repository: 1es
          type: git
          name: 1ESPipelineTemplates/1ESPipelineTemplates
          ref: refs/tags/release
    pipelines:
        - pipeline: officialBuild
          project: internal
          source: nodejs-library.official
          branch: v4.x

extends:
    template: v1/1ES.Official.PipelineTemplate.yml@1es
    parameters:
        sdl:
            sourceAnalysisPool:
                name: 1es-pool-azfunc
                image: 1es-windows-2022
                os: windows
            codeql:
                runSourceLanguagesInSourceAnalysis: true

        stages:
            - stage: Release
              pool:
                  name: 1es-pool-azfunc
                  image: 1es-ubuntu-22.04
                  os: linux
              jobs:
                  - job: Release
                    steps:
                        - download: officialBuild
                        - task: NodeTool@0
                          displayName: 'Install Node.js'
                          inputs:
                              versionSpec: 18.x
                        - script: npm ci
                          displayName: 'npm ci'
                        - script: 'npm run validateRelease -- --publishTag ${{ parameters.NpmPublishTag }} --dropPath "$(Pipeline.Workspace)/officialBuild/drop"'
                          displayName: 'validate release'
                        - script: mv *.tgz package.tgz
                          displayName: 'Rename tgz file' # because the publish command below requires an exact path
                          workingDirectory: '$(Pipeline.Workspace)/officialBuild/drop'
                        - task: Npm@1
                          displayName: 'npm publish'
                          inputs:
                              command: custom
                              workingDir: '$(Pipeline.Workspace)/officialBuild/drop'
                              verbose: true
                              customCommand: 'publish package.tgz --tag ${{ parameters.NpmPublishTag }} --dry-run ${{ lower(parameters.NpmPublishDryRun) }}'
                              customEndpoint: nodejs-library-npm
